language: python
python: 2.7
env:
  - TOX_ENV=py27-django15
  - TOX_ENV=py27-django16
  - TOX_ENV=py27-django17
  - TOX_ENV=py27-django18
  - TOX_ENV=py32-django15
  - TOX_ENV=py32-django16
  - TOX_ENV=py32-django17
  - TOX_ENV=py32-django18
  - TOX_ENV=py33-django15
  - TOX_ENV=py33-django16
  - TOX_ENV=py33-django17
  - TOX_ENV=py33-django18
  - TOX_ENV=py34-django15
  - TOX_ENV=py34-django16
  - TOX_ENV=py34-django17
  - TOX_ENV=py34-django18
  - TOX_ENV=pypy-django15
  - TOX_ENV=pypy-django16
  - TOX_ENV=pypy-django17
  - TOX_ENV=pypy-django18
  - TOX_ENV=pypy3-django15
  - TOX_ENV=pypy3-django16
  - TOX_ENV=pypy3-django17
  - TOX_ENV=pypy3-django18
  - TOX_ENV=docs
  - TOX_ENV=flake8
before_install:
# We need GraphViz for call graph generation tests
 - "sudo apt-get install graphviz 2>&1 | tail -n 2"
install:
  - pip install tox==1.9.2
script:
  - tox -e $TOX_ENV
